services:
  backend:
    build: .
    container_name: gen-video-backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    network_mode: host

  telegram-bot:
    build: .
    container_name: gen-video-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      BACKEND_URL: http://127.0.0.1:8000
    command: python bot.py
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    depends_on:
      - backend
    network_mode: host
